# Generated by Django 2.2.5 on 2021-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealproduct',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
