# Generated by Django 2.2.5 on 2021-11-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dealproduct_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='lender_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Insurance'), (2, 'Mortgage')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
