# Generated by Django 2.2.5 on 2021-11-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211124_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealproduct',
            name='lender',
        ),
    ]
