# Generated by Django 2.2.5 on 2021-11-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211124_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lender',
            new_name='provider',
        ),
        migrations.RemoveField(
            model_name='dealproduct',
            name='provider',
        ),
        migrations.AddField(
            model_name='dealproduct',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Lender'),
        ),
    ]
