# Generated by Django 2.2.5 on 2021-11-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211124_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealproduct',
            name='product_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Insurance'), (2, 'Mortgage')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.Provider'),
        ),
    ]
