# Generated by Django 2.2.5 on 2021-11-26 16:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211126_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Leads Converted'), (2, 'Not Proceeding'), (3, 'Pending Cases'), (4, 'Referrals to 3rd Party'), (5, 'Completed Mortgages'), (6, 'Insurance Policies Sold')], max_length=11, null=True),
        ),
    ]
