# Generated by Django 2.2.5 on 2021-12-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_deal_status_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Status'),
        ),
    ]
