# Generated by Django 2.2.5 on 2021-12-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Deal'),
        ),
    ]
