# Generated by Django 2.2.5 on 2021-12-13 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_dealproduct_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='readed_admin',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
