# Generated by Django 2.2.5 on 2021-12-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20211213_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='readed',
        ),
    ]
