# Generated by Django 2.2.5 on 2021-12-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
