# Generated by Django 2.2.5 on 2021-12-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_notification_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='message',
        ),
    ]
