# Generated by Django 2.2.5 on 2021-12-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_status_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='status_from',
        ),
    ]
