# Generated by Django 2.2.5 on 2021-12-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_deal_status_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
