# Generated by Django 2.2.5 on 2021-12-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_deal_status_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydeal',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
