# Generated by Django 2.2.5 on 2021-12-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_historydeal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
