# Generated by Django 2.2.5 on 2021-12-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_deal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_uuid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
