# Generated by Django 2.2.5 on 2021-12-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_task_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
