# Generated by Django 2.2.5 on 2021-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
