# Generated by Django 2.2.5 on 2021-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
