# Generated by Django 2.2.5 on 2021-12-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_token_paying_broker',
            field=models.BooleanField(default=False),
        ),
    ]
